"""ChromaPulse store-asset pipeline.

One-stop validate + optimize + prune for everything under `store_assets/`.

    python tools/store_asset_pipeline.py            # validate + optimize in place
    python tools/store_asset_pipeline.py --prune    # also delete legacy dirs
    python tools/store_asset_pipeline.py --dry-run  # report only, no writes

Optimization keeps every image under MAX_KB by:
  1. stripping metadata
  2. palette-quantizing (256 colors) when alpha isn't needed
  3. PIL `optimize=True` on final save

Validation enforces the exact dimensions each store requires. Anything wrong
prints a red FAIL line and exits non-zero, so CI can gate on this.
"""
from __future__ import annotations

import argparse
import os
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "store_assets"

MAX_KB = 500            # target per screenshot; store caps are higher but this stays snappy
ICON_MAX_KB = 200       # icons compress much better
FEATURE_MAX_KB = 300

LEGACY_DIRS = ["phone", "tablet", "raw", "raw_cropped"]

# Derived sets: (src_dir, dst_dir, (dst_w, dst_h))
# Generated by resizing from an existing set rather than re-painting.
DERIVED: list[tuple[str, str, tuple[int, int]]] = [
    ("ios", "ios_65", (1284, 2778)),  # 6.5" iPhone from 6.9" source
]


@dataclass
class Spec:
    path: str          # relative to store_assets/
    width: int
    height: int
    max_kb: int
    required: bool = True


# Exact store requirements. Update here if a platform changes its spec.
REQUIRED: list[Spec] = [
    # Marketing / top-level
    Spec("feature_graphic_1024x500.png", 1024, 500,  FEATURE_MAX_KB),
    Spec("og_card_1200x630.png",         1200, 630,  FEATURE_MAX_KB),

    # Google Play icon
    Spec("android/icon-512.png",         512,  512,  ICON_MAX_KB),

    # Google Play phone screenshots (16:9 portrait at 1080×2400 is accepted;
    # Play accepts 320-3840px on each edge as long as aspect ratio is 16:9 / 9:16).
    *[Spec(f"android/{n}", 1080, 2400, MAX_KB) for n in [
        "01_menu.png", "02_shade_hunter.png", "03_color_alchemist.png",
        "04_chroma_recall.png", "05_stats.png", "06_shop.png",
    ]],

    # App Store iPhone 6.9" (1290x2796).
    *[Spec(f"ios/{n}", 1290, 2796, MAX_KB) for n in [
        "01_menu.png", "02_shade_hunter.png", "03_color_alchemist.png",
        "04_chroma_recall.png", "05_stats.png", "06_shop.png",
    ]],

    # App Store iPhone 6.5" (1284x2778) — ASC's alternate iPhone slot.
    # Apple requires ONE OF {6.9", 6.5"}; providing both covers either slot.
    *[Spec(f"ios_65/{n}", 1284, 2778, MAX_KB) for n in [
        "01_menu.png", "02_shade_hunter.png", "03_color_alchemist.png",
        "04_chroma_recall.png", "05_stats.png", "06_shop.png",
    ]],

    # App Store iPad 13" (required since ChromaPulse supports iPad).
    *[Spec(f"ipad/{n}", 2064, 2752, MAX_KB) for n in [
        "01_menu.png", "02_shade_hunter.png", "03_color_alchemist.png",
        "04_chroma_recall.png", "05_stats.png", "06_shop.png",
    ]],
]


# --- helpers ---------------------------------------------------------------

def _kb(p: Path) -> int:
    return p.stat().st_size // 1024


def _open(p: Path) -> Image.Image:
    return Image.open(p)


def _save_optimized(img: Image.Image, dst: Path, target_kb: int) -> int:
    """Save `img` to `dst`, progressively harder compression until it fits."""
    dst.parent.mkdir(parents=True, exist_ok=True)

    # Pass 1: plain optimized PNG (drops metadata, reorders filters).
    rgb_or_rgba = "RGBA" if img.mode in ("RGBA", "LA") and _has_alpha(img) else "RGB"
    base = img.convert(rgb_or_rgba)
    base.save(dst, "PNG", optimize=True)
    if _kb(dst) <= target_kb:
        return _kb(dst)

    # Pass 2: palette quantize (256 colors). Works when there are few
    # distinct colors — perfect for flat UI screenshots.
    try:
        if rgb_or_rgba == "RGB":
            pal = base.quantize(colors=256, method=Image.Quantize.LIBIMAGEQUANT) \
                if hasattr(Image, "Quantize") else base.convert("P", palette=Image.ADAPTIVE, colors=256)
        else:
            pal = base.convert("P", palette=Image.ADAPTIVE, colors=256)
        pal.save(dst, "PNG", optimize=True)
        if _kb(dst) <= target_kb:
            return _kb(dst)
    except Exception:
        pass

    # Pass 3: fewer colors. Flat UI still looks fine at 128.
    try:
        pal = base.convert("P", palette=Image.ADAPTIVE, colors=128)
        pal.save(dst, "PNG", optimize=True)
        if _kb(dst) <= target_kb:
            return _kb(dst)
    except Exception:
        pass

    # Pass 4: last resort for gradient-heavy UIs. 64 colors with Floyd-Steinberg
    # dither preserves perceived smoothness while slashing palette size.
    try:
        pal = base.convert("P", palette=Image.ADAPTIVE, colors=64,
                           dither=Image.Dither.FLOYDSTEINBERG)
        pal.save(dst, "PNG", optimize=True)
    except Exception:
        pass
    return _kb(dst)


def _has_alpha(img: Image.Image) -> bool:
    if img.mode == "RGBA":
        alpha = img.split()[-1]
        return alpha.getextrema()[0] < 255
    return False


# --- pipeline stages -------------------------------------------------------

def validate(verbose: bool = True) -> tuple[int, int]:
    ok = fail = 0
    for s in REQUIRED:
        p = OUT / s.path
        if not p.exists():
            if s.required:
                print(f"  FAIL missing: {s.path}")
                fail += 1
            continue
        try:
            w, h = _open(p).size
        except Exception as e:
            print(f"  FAIL unreadable: {s.path} ({e})")
            fail += 1
            continue
        if (w, h) != (s.width, s.height):
            print(f"  FAIL dims:    {s.path}  got {w}x{h}  expected {s.width}x{s.height}")
            fail += 1
            continue
        kb = _kb(p)
        marker = "OK  " if kb <= s.max_kb else "HEAVY"
        if verbose:
            print(f"  {marker} {s.path}  {w}x{h}  {kb}KB  (cap {s.max_kb})")
        ok += 1
    return ok, fail


def optimize(dry_run: bool) -> int:
    touched = 0
    for s in REQUIRED:
        p = OUT / s.path
        if not p.exists():
            continue
        kb = _kb(p)
        if kb <= s.max_kb:
            continue
        if dry_run:
            print(f"  WOULD optimize: {s.path}  {kb}KB -> target {s.max_kb}KB")
            touched += 1
            continue
        new_kb = _save_optimized(_open(p), p, s.max_kb)
        verdict = "ok" if new_kb <= s.max_kb else "still heavy"
        print(f"  optimized: {s.path}  {kb}KB -> {new_kb}KB  ({verdict})")
        touched += 1
    return touched


def derive(dry_run: bool) -> int:
    """Generate alternate-size sets by resizing from a source dir."""
    made = 0
    for src_name, dst_name, (dw, dh) in DERIVED:
        src = OUT / src_name
        dst = OUT / dst_name
        if not src.exists():
            print(f"  skip: source {src_name}/ missing")
            continue
        for f in sorted(src.glob("*.png")):
            out = dst / f.name
            if out.exists() and _open(out).size == (dw, dh):
                continue
            if dry_run:
                print(f"  WOULD derive: {dst_name}/{f.name}  ({dw}x{dh})")
                made += 1
                continue
            img = _open(f).convert("RGB").resize((dw, dh), Image.LANCZOS)
            out.parent.mkdir(parents=True, exist_ok=True)
            img.save(out, "PNG", optimize=True)
            print(f"  derived: {dst_name}/{f.name}  ({dw}x{dh})  {_kb(out)}KB")
            made += 1
    return made


def prune(dry_run: bool) -> int:
    removed = 0
    for d in LEGACY_DIRS:
        p = OUT / d
        if not p.exists():
            continue
        if dry_run:
            print(f"  WOULD delete: store_assets/{d}/")
        else:
            shutil.rmtree(p)
            print(f"  deleted:      store_assets/{d}/")
        removed += 1
    return removed


# --- CLI -------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser(description="ChromaPulse store asset pipeline")
    ap.add_argument("--prune", action="store_true",
                    help="Delete legacy/redundant dirs (phone, tablet, raw, raw_cropped).")
    ap.add_argument("--dry-run", action="store_true",
                    help="Report only; no file writes.")
    ap.add_argument("--skip-optimize", action="store_true",
                    help="Validate only.")
    args = ap.parse_args()

    if not OUT.exists():
        print(f"ERROR: {OUT} not found — run from repo root.", file=sys.stderr)
        return 2

    print("=== ChromaPulse store-asset pipeline ===")
    print(f"Target dir: {OUT}\n")

    print("-- [1/4] derive alternate sizes -------------------------")
    n = derive(dry_run=args.dry_run)
    print(f"   {n} image(s) {'flagged' if args.dry_run else 'generated'}\n")

    print("-- [2/4] validate ---------------------------------------")
    ok, fail = validate()
    print(f"   {ok} ok, {fail} failed\n")

    if not args.skip_optimize:
        print("-- [3/4] optimize heavy images --------------------------")
        n = optimize(dry_run=args.dry_run)
        print(f"   {n} image(s) {'flagged' if args.dry_run else 'processed'}\n")

    if args.prune:
        print("-- [4/4] prune legacy dirs ------------------------------")
        n = prune(dry_run=args.dry_run)
        print(f"   {n} dir(s) {'flagged' if args.dry_run else 'removed'}\n")
    else:
        print("-- [4/4] prune ------------------------------------------")
        print("   skipped (pass --prune to delete legacy dirs)\n")

    # Final re-validate (quiet) so the exit code reflects post-optimize state.
    print("-- final check ------------------------------------------")
    ok, fail = validate(verbose=False)
    print(f"   {ok} assets present and sized correctly, {fail} issues")
    return 0 if fail == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
